export const CREATEJOB = 'CREATE_JOB';
export const CREATEJOBSTART = 'CREATE_JOB_START';
export const CREATEJOBSUCCESS = 'CREATE_JOB_SUCCESS';
export const CREATEJOBFAIL = 'CREATE_JOB_FAIL';
export const EDITJOB = 'EDIT_JOB';
export const DELETEJOB = 'DELETE_JOB';

//============================= Company ==============================
export const CREATECOMPANY = 'CREATE_COMPANY';
export const CREATECOMPANYFAIL = 'CREATE_COMPANY_FAIL';
export const CREATECOMPANYSTART = 'CREATE_COMPANY_START';

export const GETCOMPANY = 'GET_COMPANY';
export const GETCOMPANYFAIL = 'GET_COMPANY_FAIL';
export const GETCOMPANYSTART = 'GET_COMPANY_START';

export const UPDATECOMPANY = 'UPDATE_COMPANY';
export const UPDATECOMPANYFAIL = 'UPDATE_COMPANY_FAIL';
export const UPDATECOMPANYSTART = 'UPDATE_COMPANY_START';

export const EDITCOMPANYINTRO = 'EDIT_COMPANY_INTRO';
export const EDITCOMPANYMISSION = 'EDIT_COMPANY_MISSION';
export const EDITCOMPANYDETAILS = 'EDIT_COMPANY_DETAILS';
export const DELETECOMPANY = 'DELETE_COMPANY';
export const COMPANYRESET = 'COMPANY_RESET';

//============================= Applicant ==============================
export const CREATEAPPLICANTSUCCESS = 'CREATE_SUCCESS_APPLICANT';
export const CREATEAPPLICANTFAIL = 'CREATE_APPLICANT_FAIL';
export const CREATEAPPLICANTSTART = 'CREATE_APPLICANT_START';

export const UPDATEAPPLICANT = 'UPDATE_APPLICANT';
export const UPDATEAPPLICANTFAIL = 'UPDATE_APPLICANT_FAIL';
export const UPDATEAPPLICANTSTART = 'UPDATE_APPLICANT_START';

export const GETAPPLICANT = 'GET_APPLICANT';
export const GETAPPLICANTFAIL = 'GET_APPLICANT_FAIL';
export const GETAPPLICANTSTART = 'GET_APPLICANT_START';

export const CREATEAPPLICANTSKILL = 'CREATE_APPLICANT_SKILL';
export const EDITAPPLICANTSKILL = 'EDIT_APPLICANT_SKILL';
export const DELETESEGMENT = 'DELETE_SEGMENT';

//============================= Admin ==============================
export const GETALLAPPLICANT = 'GET_ALL_APPLICANT';
export const GETALLAPPLICANTFAIL = 'GET_ALL_APPLICANT_FAIL';
export const GETALLAPPLICANTSTART = 'GET_ALL_APPLICANT_START';

export const GETALLCOMPANY = 'GET_ALL_COMPANY';
export const GETALLCOMPANYFAIL = 'GET_ALL_COMPANY_FAIL';
export const GETALLCOMPANYSTART = 'GET_ALL_COMPANY_START';

export const GETALLJOB = 'GET_ALL_JOB';
export const GETALLJOBFAIL = 'GET_ALL_JOB_FAIL';
export const GETALLJOBSTART = 'GET_ALL_JOB_START';

//============================= FeedBack ==============================
export const CREATEFEEDBACKSUCCESS = 'CREATE_FEEDBACK_SUCCESS';
export const CREATEFEEDBACKFAIL = 'CREATE_FEEDBACK_FAIL';
export const CREATEFEEDBACKSTART = 'CREATE_FEEDBACKS_TART';

export const GETFEEDBACKSUCCESS = 'GET_FEEDBACK_SUCCESS';
export const GETFEEDBACKFAIL = 'GET_FEEDBACK_FAIL';
export const GETFEEDBACKSTART = 'GET_FEEDBACKS_TART';

export const DELETEFEEDBACK = 'DELETE_FEEDBACK';
export const DELETEFEEDBACKFAIL = 'DELETE_FEEDBACK_FAIL';
export const DELETEFEEDBACKSTART = 'DELETE_FEEDBACKS_TART';

//============================= Auth ==============================

export const AUTHADMINSTART = 'AUTH_ADMIN_START';
export const AUTHADMINFINISH = 'AUTH_ADMIN_FINISH';
export const AUTHADMINFAIL = 'AUTH_ADMIN_FAIL';
export const ADMINLOGOUT = 'ADMIN_LOGOUT';
export const AUTHADMIN = 'AUTH_ADMIN';
export const AUTHCOMPANY = 'AUTH_COMPANY';
export const AUTHLOGIN = 'AUTH_LOGIN';
export const AUTHLOGINSTART = 'AUTH_LOGIN_START';
export const AUTHLOGINFAIL = 'AUTH_LOGIN_FAIL';
export const AUTHLOGOUT = 'AUTH_LOGOUT';

export const FETCHINGSTART = 'FETCHING_START';
export const FETCHINGFAIL = 'FETCHING_FAIL';
export const FETCHINGFINISH = 'FETCHING_FINISH';
