export const CREATEJOB = 'CREATE_JOB';
export const CREATEJOBSTART = 'CREATE_JOB_START';
export const CREATEJOBSUCCESS = 'CREATE_JOB_SUCCESS';
export const CREATEJOBFAIL = 'CREATE_JOB_FAIL';
export const EDITJOB = 'EDIT_JOB';
export const DELETEJOB = 'DELETE_JOB';

export const UPDATECOMPANY = 'UPDATE_COMPANY';
export const UPDATECOMPANYFAIL = 'UPDATE_COMPANY_FAIL';
export const UPDATECOMPANYSTART = 'UPDATE_COMPANY_START';

export const CREATEAPPLICANTSUCCESS = 'CREATE_SUCCESS_APPLICANT';
export const CREATEAPPLICANTFAIL = 'CREATE_APPLICANT_FAIL';
export const CREATEAPPLICANTSTART = 'CREATE_APPLICANT_START';

export const UPDATEAPPLICANT = 'UPDATE_APPLICANT';
export const UPDATEAPPLICANTFAIL = 'UPDATE_APPLICANT_FAIL';
export const UPDATEAPPLICANTSTART = 'UPDATE_APPLICANT_START';

export const GETAPPLICANT = 'GET_APPLICANT';
export const GETAPPLICANTFAIL = 'GET_APPLICANT_FAIL';
export const GETAPPLICANTSTART = 'GET_APPLICANT_START';

export const CREATEAPPLICANTEDUCATION = 'CREATE_APPLICANT_EDUCATION';
export const CREATEAPPLICANTEXPERIENCE = 'CREATE_APPLICANT_EXPERIENCE';
export const CREATEAPPLICANTCERTIFICATION = 'CREATE_APPLICANT_CERTIFICATION';
export const CREATEAPPLICANTSKILL = 'CREATE_APPLICANT_SKILL';

export const CREATECOMPANY = 'CREATE_COMPANY';
export const CREATECOMPANYFAIL = 'CREATE_COMPANY_FAIL';
export const CREATECOMPANYSTART = 'CREATE_COMPANY_START';
export const EDITCOMPANYINTRO = 'EDIT_COMPANY_INTRO';
export const EDITCOMPANYMISSION = 'EDIT_COMPANY_MISSION';
export const EDITCOMPANYDETAILS = 'EDIT_COMPANY_DETAILS';
export const DELETECOMPANY = 'DELETE_COMPANY';
export const COMPANYRESET = 'COMPANY_RESET';

export const EDITAPPLICANTINTRO = 'EDIT_APPLICANT_INTRO';
export const EDITAPPLICANTSUMMARY = 'EDIT_APPLICANT_SUMMARY';
export const EDITAPPLICANTEDUCATION = 'EDIT_APPLICANT_EDUCATION';
export const EDITAPPLICANTEXPERIENCE = 'EDIT_APPLICANT_EXPERIENCE';
export const EDITAPPLICANTCERTIFICATION = 'EDIT_APPLICANT_CERTIFICATION';
export const EDITAPPLICANTSKILL = 'EDIT_APPLICANT_SKILL';
export const DELETESEGMENT = 'DELETE_SEGMENT';

export const CREATEFEEDBACK = 'CREATE_FEEDBACK';
export const DELETEFEEDBACK = 'DELETE_FEEDBACK';

export const AUTHADMIN = 'AUTH_ADMIN';
export const AUTHCOMPANY = 'AUTH_COMPANY';
export const AUTHLOGIN = 'AUTH_LOGIN';
export const AUTHLOGOUT = 'AUTH_LOGOUT';
