const EducationMajor = [
  { major: 'Administrasi Bisnis' },
  { major: 'Administrasi Fiskal' },
  { major: 'Administrasi Keuangan' },
  { major: 'Administrasi Niaga' },
  { major: 'Administrasi Pendidikan' },
  { major: 'Administrasi Publik' },
  { major: 'Agribisnis (Sosial Ekonomi Pertanian)' },
  { major: 'Agrobisnis Perikanan (Sosial Ekonomi Perikanan)' },
  { major: 'Agroeteknologi' },
  { major: 'Agronomi dan Hortikultura' },
  { major: 'Agroteknologi' },
  { major: 'Aktuaria' },
  { major: 'Akuntansi' },
  { major: 'Akuntansi Bisnis' },
  { major: 'Akuntansi Sektor Publik' },
  { major: 'Animasi' },
  { major: 'Antropologi' },
  { major: 'Arkeologi' },
  { major: 'Arsitektur' },
  { major: 'Arsitektur Lanskap' },
  { major: 'Astronomi' },
  { major: 'Audio Engineering' },
  { major: 'Automotive and Robotics Engineering' },
  { major: 'Bioentrepreneurship' },
  { major: 'Bioinformatika' },
  { major: 'Biokimia' },
  { major: 'Biologi' },
  { major: 'Bioteknologi' },
  { major: 'Bisnis Internasional' },
  { major: 'Bisnis Islam' },
  { major: 'Branding' },
  { major: 'Budidaya Perairan (Akuakultur)' },
  { major: 'Budidaya Perikanan' },
  { major: 'Business Creation' },
  { major: 'Business Law' },
  { major: 'Computerized Accounting' },
  { major: 'Cyber Security' },
  { major: 'Desain Grafis' },
  { major: 'Desain Interior' },
  { major: 'Desain Produk' },
  { major: 'DKV Creative Advertising' },
  { major: 'DKV New Media' },
  { major: 'Ekonomi' },
  { major: 'Ekonomi Bisnis' },
  { major: 'Ekonomi Pembangunan' },
  { major: 'Ekonomi Syariah' },
  { major: 'Farmasi' },
  { major: 'Filsafat' },
  { major: 'Fisika' },
  { major: 'Fisika Medis' },
  { major: 'Fisioterafi' },
  { major: 'Furniture Design' },
  { major: 'Geofisika' },
  { major: 'Geografi' },
  { major: 'Green Economy' },
  { major: 'Hubungan Internasional (HI)' },
  { major: 'Hubungan Masyarakat' },
  { major: 'Human Computer Interaction' },
  { major: 'Ilmu Gizi' },
  { major: 'Ilmu Hama dan Penyakit Tumbuhan (Proteksi Tanaman)' },
  { major: 'Ilmu Hukum' },
  { major: 'Ilmu Kelautan' },
  { major: 'Ilmu Keluarga dan Konsumen' },
  { major: 'Ilmu Keolahragaan' },
  { major: 'Ilmu Keperawatan' },
  { major: 'Ilmu Kesejahteraan Sosial' },
  { major: 'Ilmu Komputasi' },
  { major: 'Ilmu Komputer' },
  { major: 'Ilmu Komunikasi' },
  { major: 'Ilmu Pangan (Food Science)' },
  { major: 'Ilmu Pemerintahan' },
  { major: 'Ilmu Perpustakaan' },
  { major: 'Ilmu Sejarah' },
  { major: 'Industrial RoboticsDesign' },
  { major: 'Information Systems Audit' },
  { major: 'Jurnalistik' },
  { major: 'Kartografi dan Penginderaan Jauh' },
  { major: 'Kearsipan' },
  { major: 'Kebidanan' },
  { major: 'Kedokteran Gigi' },
  { major: 'Kedokteran Hewan' },
  { major: 'Kehutanan' },
  { major: 'Kesehatan Lingkungan' },
  { major: 'Kesehatan Masyarakat' },
  { major: 'Keselamatan & Kesehatan Kerja' },
  { major: 'Keuangan' },
  { major: 'Kewirausahaan' },
  { major: 'Kimia' },
  { major: 'Komunikasi Penerbangan' },
  { major: 'Konservasi Sumberdaya Hutan dan Ekowisata' },
  { major: 'Kriminologi' },
  { major: 'Kurikulum dan Teknologi Pendidikan' },
  { major: 'Lalu Lintas Udara' },
  { major: 'llmu Politik' },
  { major: 'Manajemen' },
  { major: 'Manajemen Bisnis' },
  { major: 'Manajemen Bisnis dan Pemasaran' },
  { major: 'Manajemen Bisnis Internasional' },
  { major: 'Manajemen Bisnis Telekomunikasi Informatika' },
  { major: 'Manajemen Bisnis Unggas' },
  { major: 'Manajemen Hutan' },
  { major: 'Manajemen Industri Katering' },
  { major: 'Manajemen Informatika' },
  { major: 'Manajemen Keuangan' },
  { major: 'Manajemen Keuangan Syariah' },
  { major: 'Manajemen Komunikasi' },
  { major: 'Manajemen Logistik' },
  { major: 'Manajemen Operasi' },
  { major: 'Manajemen Pariwisata' },
  { major: 'Manajemen Pelayanan Rumah Sakit' },
  { major: 'Manajemen Pemasaran' },
  { major: 'Manajemen Pendidikan' },
  { major: 'Manajemen Pendidikan Islam' },
  { major: 'Manajemen Produksi Media' },
  { major: 'Manajemen Rekayasa Industri' },
  { major: 'Manajemen Sumber Daya Manusia dan Organisasi' },
  { major: 'Manajemen Sumber Daya Perairan' },
  { major: 'Manajemen Sumberdaya Lahan (Ilmu Tanah)' },
  { major: 'Manajemen Transportasi' },
  { major: 'Marketing' },
  { major: 'Marketing Communication' },
  { major: 'Matematika' },
  { major: 'Matematika Bisnis' },
  { major: 'Meteorologi' },
  { major: 'Meteorologi Terapan' },
  { major: 'Metrologi' },
  { major: 'Mikrobiologi' },
  { major: 'Mikrobiologi Pertanian' },
  { major: 'Mobile Application & Technology' },
  { major: 'Nutrisi dan Teknologi Pangan' },
  { major: 'Oseanografi' },
  { major: 'Pariwisata' },
  { major: 'Pemanfaatan Sumberdaya Perikanan' },
  { major: 'Pemasaran Internasional' },
  { major: 'Pembangunan Sosial dan Kesejahteraan' },
  { major: 'Pendidikan Agama Islam' },
  { major: 'Pendidikan Anak Usia Dini (PAUD)' },
  { major: 'Pendidikan Bahasa Arab' },
  { major: 'Pendidikan Bahasa dan Sastra Indonesia' },
  { major: 'Pendidikan Bahasa Inggris' },
  { major: 'Pendidikan Bimbingan Konseling' },
  { major: 'Pendidikan Geografi' },
  { major: 'Pendidikan Guru Sekolah Dasar (PGSD)' },
  { major: 'Pendidikan Ilmu Pengetahuan Alam' },
  { major: 'Pendidikan Intelijen' },
  { major: 'Pendidikan Jasmani Kesehatan dan Rekreasi' },
  { major: 'Pendidikan Kepelatihan Olahraga' },
  { major: 'Pendidikan Kependudukan' },
  { major: 'Pendidikan Kepolisian' },
  { major: 'Pendidikan Luar Biasa (PLB)' },
  { major: 'Pendidikan Luar Sekolah' },
  { major: 'Pendidikan Matematika' },
  { major: 'Pendidikan Militer' },
  { major: 'Pendidikan Pancasila dan Kewarganegaraan' },
  { major: 'Pendidikan Sejarah' },
  { major: 'Penerbang (Pendidikan Pilot)' },
  { major: 'Pengelolaan dan Pemberdayaan SDA dan Lingkungan' },
  { major: 'Pengelolaan Hutan' },
  { major: 'Penyiaran (Broadcasting)' },
  { major: 'Penyuluhan dan Komunikasi Pertanian' },
  { major: 'Peradilan Agama' },
  { major: 'Periklanan (Advertiing)' },
  { major: 'Peternakan' },
  { major: 'Politik Islam' },
  { major: 'Produksi Ternak' },
  { major: 'Psikologi' },
  { major: 'Rekayasa hayati' },
  { major: 'Rekayasa Infrastruktur Lingkungan' },
  { major: 'Rekayasa Pertanian' },
  { major: 'Sains Komunikasi dan Pengembangan Masyarakat' },
  { major: 'Sastra Arab' },
  { major: 'Sastra Bali' },
  { major: 'Sastra Belanda' },
  { major: 'Sastra Cina' },
  { major: 'Sastra Indonesia' },
  { major: 'Sastra Inggris' },
  { major: 'Sastra Jawa' },
  { major: 'Sastra Jepang' },
  { major: 'Sastra Jerman' },
  { major: 'Sastra Korea' },
  { major: 'Sastra Minangkabau' },
  { major: 'Sastra Nusantara' },
  { major: 'Sastra Perancis' },
  { major: 'Sastra Rusia' },
  { major: 'Sastra Slavia' },
  { major: 'Sastra Sunda' },
  { major: 'Sejarah dan Kebudayaan Islam' },
  { major: 'Sistem dan Teknologi Informasi' },
  { major: 'Sistem Informasi (Manajemen Informatika)' },
  { major: 'Sistem Informasi Bisnis' },
  { major: 'Sistem Komputer (Teknik Komputer)' },
  { major: 'Software Engineering' },
  { major: 'Sosiologi' },
  { major: 'Statistika' },
  { major: 'Statistika Terapan' },
  { major: 'Tata Boga' },
  { major: 'Techopreneurship' },
  { major: 'Teknik Alat Berat' },
  { major: 'Teknik Bangunan dan Landasan' },
  { major: 'Teknik Bioenergi dan Kemurgi' },
  { major: 'Teknik Ekonomi Konstruksi (Quantity Surveyor)' },
  { major: 'Teknik Elektro' },
  { major: 'Teknik Fisika' },
  { major: 'Teknik Geodesi' },
  { major: 'Teknik Geologi' },
  { major: 'Teknik Geomatika' },
  { major: 'Teknik Grafika' },
  { major: 'Teknik Industri' },
  { major: 'Teknik Informatika' },
  { major: 'Teknik Kelautan' },
  { major: 'Teknik Kimia' },
  { major: 'Teknik Konversi Energi' },
  { major: 'Teknik Lingkungan' },
  { major: 'Teknik Listrik Bandara' },
  { major: 'Teknik Material' },
  { major: 'Teknik Mesin' },
  { major: 'Teknik Metalurgi' },
  { major: 'Teknik Nuklir' },
  { major: 'Teknik Otomasi Manufaktur dan Mekatronika' },
  { major: 'Teknik Otomotif' },
  { major: 'Teknik Penerbangan (Aeronautika dan Astronautika)' },
  { major: 'Teknik Pengairan (Sumber Daya Air)' },
  { major: 'Teknik Perancangan Jalan dan Jembatan' },
  { major: 'Teknik Perencanaan Wilayah dan Kota (Planologi)' },
  { major: 'Teknik Perkapalan' },
  { major: 'Teknik Perminyakan' },
  { major: 'Teknik Perpipaan' },
  { major: 'Teknik Pertambangan' },
  { major: 'Teknik Pertanian' },
  { major: 'Teknik Radiodiagnostik dan Radioterapi' },
  { major: 'Teknik Refrigerasi dan Tata Udara' },
  { major: 'Teknik Sipil' },
  { major: 'Teknik Sistem Komputer' },
  { major: 'Teknik Sistem Perkapalan' },
  { major: 'Teknik Telekomunikasi' },
  { major: 'Teknik Telekomunikasi dan Navigasi Udara' },
  { major: 'Teknik Tenaga Listrik' },
  { major: 'Teknobiomedik' },
  { major: 'Teknologi Bioproses' },
  { major: 'Teknologi Game' },
  { major: 'Teknologi Hasil Hutan' },
  { major: 'Teknologi Hasil Perikanan' },
  { major: 'Teknologi Hasil Ternak' },
  { major: 'Teknologi Industri Benih' },
  { major: 'Teknologi Industri Pertanian (Agroindustri)' },
  { major: 'Teknologi Pangan' },
  { major: 'Teknologi Pasca Panen' },
  { major: 'Teologi' },
  { major: 'Transportasi Laut' },
];
export default EducationMajor;
