const IndustryData = [
  { industry: 'Aerospace' },
  { industry: 'Agriculture' },
  { industry: 'Architecture' },
  { industry: 'Banking' },
  { industry: 'Biology' },
  { industry: 'Business' },
  { industry: 'Chemistry' },
  { industry: 'Commerce' },
  { industry: 'Communication' },
  { industry: 'Construction' },
  { industry: 'Counseling' },
  { industry: 'E-Commerce' },
  { industry: 'Economy' },
  { industry: 'Education' },
  { industry: 'Entertainment' },
  { industry: 'Fishery' },
  { industry: 'Food & Baverage' },
  { industry: 'Forestry' },
  { industry: 'Health' },
  { industry: 'Hospitality' },
  { industry: 'Interior Design' },
  { industry: 'International Relation' },
  { industry: 'Information Technology' },
  { industry: 'Journalism' },
  { industry: 'Law & Order' },
  { industry: 'Logistic' },
  { industry: 'Management' },
  { industry: 'Manufacture' },
  { industry: 'Medical Doctor' },
  { industry: 'Oil & Gas' },
  { industry: 'Pharmacy' },
  { industry: 'Photography' },
  { industry: 'Property' },
  { industry: 'Psychology' },
  { industry: 'Public Health' },
  { industry: 'Science' },
  { industry: 'Shipping' },
  { industry: 'Social & Politics' },
  { industry: 'Sport' },
  { industry: 'Tax' },
  { industry: 'Tourism' },
  { industry: 'Training & Development' },
  { industry: 'Veterinarian' },
  { industry: 'Distribution' },
  { industry: 'Telco' },
  { industry: 'Transportation' },
  { industry: 'News & Information' },
  { industry: 'Traveling' },
  { industry: 'Consulting' },
  { industry: 'Fashion' },
  { industry: 'Technology' },
  { industry: 'Investment' },
];
export default IndustryData;
