const UniversityList = [
  'Universitas Gadjah Mada',
  'Universitas Indonesia',
  'Universitas Pendidikan Indonesia',
  'Universitas Diponegoro',
  'Universitas Brawijaya',
  'Universitas Negeri Yogyakarta',
  'Universitas Lampung',
  'Universitas Airlangga',
  'Institut Pertanian Bogor',
  'Universitas Negeri Semarang',
  'Universitas Muhammadiyah Surakarta',
  'Institut Teknologi Bandung',
  'Universitas Negeri Malang',
  'Universitas Sumatera Utara',
  'Universitas Muhammadiyah Yogyakarta',
  'Universitas Bina Nusantara',
  'Universitas Telkom',
  'Institut Teknologi Sepuluh Nopember',
  'Universitas Jember',
  'Universitas Udayana',
  'Universitas Islam Negeri Maulana Malik Ibrahim Malang',
  'Universitas Andalas',
  'Universitas Sebelas Maret',
  'Universitas Hasanuddin',
  'Universitas Islam Negeri Syarif Hidayatullah Jakarta',
  'Universitas Muhammadiyah Malang',
  'Universitas Islam Negeri Sunan Ampel Surabaya',
  'Universitas Islam Indonesia',
  'Universitas Islam Negeri Walisongo',
  'Universitas Islam Negeri Sulthan Syarif Kasim Riau',
  'Universitas Pasundan',
  'Universitas Negeri Surabaya',
  'Universitas Syiah Kuala',
  'Universitas Mercu Buana',
  'Universitas Gunadarma',
  'Universitas Islam Negeri Sunan Kalijaga Yogyakarta',
  'Universitas Jambi',
  'Universitas Ahmad Dahlan',
  'Universitas Dian Nuswantoro',
  'Universitas Sriwijaya',
  'Universitas Islam Negeri Alauddin Makassar',
  'Universitas Sam Ratulangi',
  'Universitas Negeri Padang',
  'Universitas Sanata Dharma',
  'Universitas Narotama',
  'Universitas Komputer Indonesia',
  'Universitas Mataram',
  'Universitas Jenderal Soedirman',
  'Universitas Muhammadiyah Purwokerto',
  'Universitas Atma Jaya Yogyakarta',
  'Universitas Padjadjaran',
  'Universitas Bengkulu',
  'Universitas Muhammadiyah Sumatera Utara',
  'Universitas Islam Sultan Agung',
  'Universitas Esa Unggul',
  'Universitas Islam Negeri Sunan Gunung Djati',
  'Universitas Kristen Petra',
  'Universitas Muhammadiyah Ponorogo',
  'Universitas Pendidikan Ganesha Universitas Riau',
  'Universitas Muhammadiyah Semarang',
  'Universitas Islam Bandung',
  'Universitas Sarjanawiyata Tamansiswa',
  'Universitas Islam Negeri Sumatera Utara',
  'Universitas Mulawarman',
  'Universitas Widyatama',
  'Universitas Tanjungpura',
  'Universitas Tadulako',
  'Universitas Negeri Medan',
  'Universitas Islam Negeri Raden Intan Lampung Bandar',
  'Universitas Lambung Mangkurat',
  'Institut Seni Indonesia Surakarta',
  'Universitas Negeri Makassar',
  'Universitas Negeri Jakarta',
  'Universitas Trunojoyo Madura',
  'Universitas Pelita Harapan',
  'Universitas Darma Persada',
  'Universitas Medan Area',
  'Universitas Kristen Maranatha',
  'Universitas Pembangunan Nasional Veteran Jawa Timur',
  'Universitas Surabaya',
  'Universitas Mercu Buana Yogyakarta',
  'Universitas Muhammadiyah Metro',
  'Universitas Katolik Soegijapranata',
  'Universitas Katolik Parahyangan',
  'Universitas PGRI Madiun',
  'Universitas Muhammadiyah Sidoarjo',
  'Universitas Islam Negeri Raden Fatah',
  'Universitas Swadaya Gunung Jati',
  'Universitas Katolik Indonesia Atma Jaya',
  'Universitas 17 Agustus 1945 Surabaya',
  'Institut Teknologi Nasional',
  'Universitas Islam Negeri Ar-Raniry',
  'Institut Seni Indonesia Denpasar',
  'Universitas Kristen Satya Wacana',
  'Universitas Trisakti',
  'Universitas Halu Oleo',
  'Universitas Bina Darma',
  'Universitas Muria Kudus',
  'Universitas Wahid Hasyim',
];

export default UniversityList;
