const WorkList = [
	'Accounting',
	'Admin',
	'Aerospace',
	'Agriculture',
	'Architecture',
	'Auditor',
	'Banking',
	'Biology',
	'Business',
	'Business Analyst',
	'Business Development',
	'Chemistry',
	'Commerce',
	'Communication',
	'Construction',
	'Consultant',
	'Counseling',
	'Data Analyst',
	'Dentist',
	'Distributor',
	'Economy',
	'Education',
	'Engineer',
	'Entertainment',
	'Finance',
	'Fishery',
	'Food & Beverages',
	'Forestry',
	'Graphic Design',
	'Health',
	'Hospitality',
	'Human Resource',
	'Information Technology',
	'Interior Design',
	'International Relation',
	'Journalism',
	'Law & Order',
	'Literature',
	'Logistic',
	'Management',
	'Manufacturing',
	'Marketing',
	'Medical Doctor',
	'Merchandiser',
	'Oil & Gas',
	'Operator',
	'Pharmacy',
	'Philosophy',
	'Photography',
	'Procurement',
	'Production',
	'Project Management',
	'Psychology',
	'Public Health',
	'Public Relation',
	'Purchasing',
	'Quality Control',
	'Research & Development',
	'Sales',
	'Science',
	'Secretary',
	'Shipping',
	'Social & Politics',
	'Sports',
	'Tax',
	'Teacher',
	'Technician',
	'Tourism',
	'Training & Development',
	'UI/UX',
	'Veterinarian',
	'Videografer'
];
export default WorkList;
