const WorkList = [
  { field: 'Accounting' },
  { field: 'Admin' },
  { field: 'Aerospace' },
  { field: 'Agriculture' },
  { field: 'Architecture' },
  { field: 'Auditor' },
  { field: 'Banking' },
  { field: 'Biology' },
  { field: 'Business' },
  { field: 'Business Analyst' },
  { field: 'Business Development' },
  { field: 'Chemistry' },
  { field: 'Commerce' },
  { field: 'Communication' },
  { field: 'Construction' },
  { field: 'Consultant' },
  { field: 'Counseling' },
  { field: 'Data Analyst' },
  { field: 'Dentist' },
  { field: 'Distributor' },
  { field: 'Economy' },
  { field: 'Education' },
  { field: 'Engineer' },
  { field: 'Entertainment' },
  { field: 'Finance' },
  { field: 'Fishery' },
  { field: 'Food & Beverages' },
  { field: 'Forestry' },
  { field: 'Graphic Design' },
  { field: 'Health' },
  { field: 'Hospitality' },
  { field: 'Human Resource' },
  { field: 'Information Technology' },
  { field: 'Interior Design' },
  { field: 'International Relation' },
  { field: 'Journalism' },
  { field: 'Law & Order' },
  { field: 'Literature' },
  { field: 'Logistic' },
  { field: 'Management' },
  { field: 'Manufacturing' },
  { field: 'Marketing' },
  { field: 'Medical Doctor' },
  { field: 'Merchandiser' },
  { field: 'Oil & Gas' },
  { field: 'Operator' },
  { field: 'Pharmacy' },
  { field: 'Philosophy' },
  { field: 'Photography' },
  { field: 'Procurement' },
  { field: 'Production' },
  { field: 'Project Management' },
  { field: 'Psychology' },
  { field: 'Public Health' },
  { field: 'Public Relation' },
  { field: 'Purchasing' },
  { field: 'Quality Control' },
  { field: 'Research & Development' },
  { field: 'Sales' },
  { field: 'Science' },
  { field: 'Secretary' },
  { field: 'Shipping' },
  { field: 'Social & Politics' },
  { field: 'Sports' },
  { field: 'Tax' },
  { field: 'Teacher' },
  { field: 'Technician' },
  { field: 'Tourism' },
  { field: 'Training & Development' },
  { field: 'UI/UX' },
  { field: 'Veterinarian' },
  { field: 'Videografer' },
];
export default WorkList;
