const WorkList = [
  "Akuntan",
  "Pajak",
  "Konsultan",
  "Auditor",
  "Bendahara",
  "Administrasi & Operasional",
  "Departemen Sumber Daya Manusia",
  "Pelatihan & Pengembangan",
  "Resepsionis",
  "Staf Admin",
  "Sekertaris",
  "Perbankan",
  "Ahli Terapi",
  "Ahli Kecantikan",
  "Kesehatan",
  "Arsitektur",
  "Konstruksi & Pembangunan",
  "Tenaga Pengajar - Guru",
  "Tenaga Pengajar - Dosen",
  "Pustakawan",
  "Desain Grafis",
  "Desain Interior",
  "UI/UX",
  "Merchandiser",
  "Pengembangan Produk",
  "Farmasi",
  "Perkapalan",
  "Kelautan",
  "Manager Proyek",
  "Teknologi Informasi",
  "Kesehatan & Keselamatan Kerja",
  "Manufaktur & Produksi",
  "Teknik Lingkungan",
  "Makanan & Minuman",
  "Hospitality",
  "Operasional",
  "Pariwisata",
  "Manajemen Umum",
  "Eksekutif Atas",
  "Perencanaan Produksi",
  "Kontrol Kualitas",
  "Pemasaran",
  "Hubungan Masyarakat",
  "Riset Pasar",
  "Jurnalis",
  "Fotografer",
  "Videografer",
  "Dokter",
  "Dokter Hewan",
  "Pembelian",
  "Data Analis",
  "Bisnis Analis",
  "Pertahanan & Keamanan",
  "Konseling",
  "Layanan Sosial",
  "Penjualan",
  "Pengembangan Bisnis",
  "Pertanian",
  "Perhutanan",
  "Sumber Daya Alam",
  "Riset & Pengembangan",
  "Trasportasi & Logistik",
  "Distributor",
  "Perikanan",
  "Perniagaan",
  "Hiburan/ Entertainment",
  "Pertambangan",
  "Perminyakan",
  "Ahli Geologi",
];
export default WorkList;
