const CitiesList = {
  Aceh: [
    'Kab. Aceh Barat',
    'Kab. Aceh Barat Daya',
    'Kab. Aceh Besar',
    'Kab. Aceh Jaya',
    'Kab. Aceh Selatan',
    'Kab. Aceh Singkil',
    'Kab. Aceh Tamiang',
    'Kab. Aceh Tengah',
    'Kab. Aceh Tenggara',
    'Kab. Aceh Timur',
    'Kab. Aceh Utara',
    'Kab. Bener Meriah',
    'Kab. Bireuen',
    'Kab. Gayo Lues',
    'Kab. Nagan Raya',
    'Kab. Pidie',
    'Kab. Pidie Jaya',
    'Kab. Simeulue',
    'Banda Aceh',
    'Langsa',
    'Lhokseumawe',
    'Sabang',
    'Subulussalam',
  ],
  Bali: [
    'Kab. Badung',
    'Kab. Bangli',
    'Kab. Buleleng',
    'Kab. Gianyar',
    'Kab. Jembrana',
    'Kab. Karang Asem',
    'Kab. Klungkung',
    'Kab. Tabanan',
    'Denpasar',
  ],
  Banten: [
    'Kab. Lebak',
    'Kab. Pandeglang',
    'Kab. Serang',
    'Kab. Tangerang',
    'Cilegon',
    'Serang',
    'Tangerang',
    'Tangerang Selatan',
  ],
  Bengkulu: [
    'Kab. Bengkulu Selatan',
    'Kab. Bengkulu Tengah',
    'Kab. Bengkulu Utara',
    'Kab. Kaur',
    'Kab. Kepahiang',
    'Kab. Lebong',
    'Kab. Muko Muko',
    'Kab. Rejang Lebong',
    'Kab. Seluma',
    'Bengkulu',
  ],
  Yogyakarta: [
    'Kab. Bantul',
    'Kab. Gunung Kidul',
    'Kab. Kulon Progo',
    'Kab. Sleman',
    'Yogyakarta',
  ],
  Jakarta: [
    'Jakarta Selatan',
    'Jakarta Pusat',
    'Jakarta Barat',
    'Jakarta Timur',
    'Jakarta Utara',
    'Kab. Pulau Seribu',
  ],
  Gorontalo: [
    'Kab. Boalemo',
    'Kab. Bone Bolango',
    'Kab. Gorontalo',
    'Kab. Gorontalo Utara',
    'Kab. Pohuwato',
    'Gorontalo',
  ],
  Jambi: [
    'Kab. Batang Hari',
    'Kab. Bungo',
    'Kab. Kerinci',
    'Kab. Merangin',
    'Kab. Sarolangun',
    'Kab. Tanjung Jabung Barat',
    'Kab. Tanjung Jabung Timur',
    'Kab. Tebo',
    'Kab. Jambi',
    'Sungai Penuh',
  ],
  JawaBarat: [
    'Kab. Bandung',
    'Kab. Bandung Barat',
    'Kab. Bekasi',
    'Kab. Bogor',
    'Kab. Ciamis',
    'Kab. Cianjur',
    'Kab. Cirebon',
    'Kab. Garut',
    'Kab. Indramayu',
    'Kab. Karawang',
    'Kab. Kuningan',
    'Kab. Majalengka',
    'Kab. Pangandaran',
    'Kab. Purwakarta',
    'Kab. Subang',
    'Kab. Sukabumi',
    'Kab. Sumedang',
    'Kab. Tasikmalaya',
    'Bandung',
    'Banjar',
    'Bekasi',
    'Bogor',
    'Cimahi',
    'Cirebon',
    'Depok',
    'Sukabumi',
    'Tasikmalaya',
  ],
  JawaTengah: [
    'Kab. Banjarnegara',
    'Kab. Banyumas',
    'Kab. Batang',
    'Kab. Blora',
    'Kab. Boyolali',
    'Kab. Brebes',
    'Kab. Cilacap',
    'Kab. Demak',
    'Kab. Grobogan',
    'Kab. Jepara',
    'Kab. Karanganyar',
    'Kab. Kebumen',
    'Kab. Kendal',
    'Kab. Klaten',
    'Kab. Kudus',
    'Kab. Magelang',
    'Kab. Pati',
    'Kab. Pekalongan',
    'Kab. Pemalang',
    'Kab. Purbalingga',
    'Kab. Purworejo',
    'Kab. Rembang',
    'Kab. Semarang',
    'Kab. Sragen',
    'Kab. Sukoharjo',
    'Kab. Tegal',
    'Kab. Temanggung',
    'Kab. Wonogiri',
    'Kab. Wonosobo',
    'Kota Magelang',
    'Kota Pekalongan',
    'Kota Salatiga',
    'Kota Semarang',
    'Kota Surakarta',
    'Kota Tegal',
  ],
  JawaTimur: [
    'Kab. Bangkalan',
    'Kab. Banyuwangi',
    'Kab. Blitar',
    'Kab. Bojonegoro',
    'Kab. Bondowoso',
    'Kab. Gresik',
    'Kab. Jember',
    'Kab. Jombang',
    'Kab. Kediri',
    'Kab. Lamongan',
    'Kab. Lumajang',
    'Kab. Madiun',
    'Kab. Magetan',
    'Kab. Malang',
    'Kab. Mojokerto',
    'Kab. Nganjuk',
    'Kab. Ngawi',
    'Kab. Pacitan',
    'Kab. Pamekasan',
    'Kab. Pasuruan',
    'Kab. Ponorogo',
    'Kab. Probolinggo',
    'Kab. Sampang',
    'Kab. Sidoarjo',
    'Kab. Situbondo',
    'Kab. Sumenep',
    'Kab. Trenggalek',
    'Kab. Tuban',
    'Kab. Tulungagung',
    'Kota Batu',
    'Kota Blitar',
    'Kota Kediri',
    'Kota Madiun',
    'Kota Malang',
    'Kota Mojokerto',
    'Kota Pasuruan',
    'Kota Probolinggo',
    'Kota Surabaya',
  ],
  KalBar: [
    'Kab. Bengkayang',
    'Kab. Kapuas Hulu',
    'Kab. Kayong Utara',
    'Kab. Ketapang',
    'Kab. Kuburaya',
    'Kab. Landak',
    'Kab. Melawi',
    'Kab. Mempawah',
    'Kab. Sambas',
    'Kab. Sanggau',
    'Kab. Sekadau',
    'Kab. Sintang',
    'Kota Pontianak',
    'Kota Singkawang',
  ],
  KalSel: [
    'Kab. Balangan',
    'Kab. Banjar',
    'Kab. Barito Kuala',
    'Kab. Hulu Sungai Selatan',
    'Kab. Hulu Sungai Tengah',
    'Kab. Hulu Sungai Utara',
    'Kab. Kotabaru',
    'Kab. Tabalong',
    'Kab. Tanah Bumbu',
    'Kab. Tanah Laut',
    'Kab. Tapin',
    'Kota Banjarbaru',
    'Kota Banjarmasin',
  ],
  KalTeng: [
    'Kab. Barito Selatan',
    'Kab. Barito Timur',
    'Kab. Barito Utara',
    'Kab. Gunung Mas',
    'Kab. Kapuas',
    'Kab. Katingan',
    'Kab. Kotawaringin Barat',
    'Kab. Kotawaringin Timur',
    'Kab. Lamandau',
    'Kab. Murung Raya',
    'Kab. Pulang Pisau',
    'Kab. Seruyan',
    'Kab. Sukamara',
    'Kota Palangka Raya',
  ],
  KalTim: [
    'Kab. Berau',
    'Kab. Kutai Barat',
    'Kab. Kutai Kartanegara',
    'Kab. Kutai Timur',
    'Kab. Mahakam Ulu',
    'Kab. Paser',
    'Kab. Penajam Paser Utara',
    'Kota Balikpapan',
    'Kota Bontang',
    'Kota Samarinda',
  ],
  KalUt: [
    'Kab. Bulungan',
    'Kab. Malinau',
    'Kab. Nunukan',
    'Kab. Tana Tidung',
    'Kota Tarakan',
  ],
  BangkaBelitung: [
    'Kab. Bangka',
    'Kab. Bangka Barat',
    'Kab. Bangka Selatan',
    'Kab. Bangka Tengah',
    'Kab. Belitung',
    'Kab. Belitung Timur',
    'Kota Pangkalpinang',
  ],
  KepulauanRiau: [
    'Kab. Bintan',
    'Kab. Karimun',
    'Kab. Kepulauan Anambas',
    'Kab. Lingga',
    'Kab. Natuna',
    'Kota Batam',
    'Kota Tanjungpinang',
  ],
  Lampung: [
    'Kab. Lampung Barat',
    'Kab. Lampung Selatan',
    'Kab. Lampung Tengah',
    'Kab. Lampung Timur',
    'Kab. Lampung Utara',
    'Kab. Mesuji',
    'Kab. Pesawaran',
    'Kab. Pesisir Barat',
    'Kab. Pringsewu',
    'Kab. Tanggamus',
    'Kab. Tulang Bawang',
    'Kab. Tulang Bawang Barat',
    'Kab. Way Kanan',
    'Kota Bandar Lampung',
    'Kota Metro',
  ],
  Maluku: [
    'Kab. Buru',
    'Kab. Buru Selatan',
    'Kab. Kepulauan Aru',
    'Kab. Kepulauan Tanimbar',
    'Kab. Maluku Barat Daya',
    'Kab. Maluku Tengah',
    'Kab. Maluku Tenggara',
    'Kab. Seram Bagian Barat',
    'Kab. Seram Bagian Timur',
    'Kota Ambon',
    'Kota Tual',
  ],
  MalukuUtara: [
    'Kab. Halmahera Barat',
    'Kab. Halmahera Selatan',
    'Kab. Halmahera Tengah',
    'Kab. Halmahera Timur',
    'Kab. halmahera Utara',
    'Kab. Kepulauan Morotai',
    'Kab. Kepulauan Sula',
    'Kab. Pulau Taliabu',
    'Kota Ternate',
    'Kota Tidore Kepulauan',
  ],
  NTB: [
    'Kab. Bima',
    'Kab. Dompu',
    'Kab. Lombok Barat',
    'Kab. Lombok Tengah',
    'Kab. Lombok Timur',
    'Kab. Lombok Utara',
    'Kab. Sumbawa',
    'Kab. Sumbawa Barat',
    'Kota Bima',
    'Kota Mataram',
  ],
  NTT: [
    'Kab. Alor',
    'Kab. Belu',
    'Kab. Ende',
    'Kab. Flores Timur',
    'Kab. Kupang',
    'Kab. Lembata',
    'Kab. Malaka',
    'Kab. Manggarai',
    'Kab. Manggarai Barat',
    'Kab. Manggarai Timur',
    'Kab. Nagakeo',
    'Kab. Ngada',
    'Kab. Rote-Ndao',
    'Kab. Sabu Raijua',
    'Kab. Sikka',
    'Kab. Sumba Barat',
    'Kab. Sumba Barat Daya',
    'Kab. Sumba Tengah',
    'Kab. Sumba Timur',
    'Kab. Timor Tengah Selatan',
    'Kab. Timor Tengah Utara',
    'Kota Kupang',
  ],
  Papua: [
    'Kab. Asmat',
    'Kab. Biak Numfor',
    'Kab. Boven Digoel',
    'Kab. Deiyai',
    'Kab. Dogiyai',
    'Kab. Intan Jaya',
    'Kab. Jaya Wijaya',
    'Kab. Jayapura',
    'Kab. Keerom',
    'Kab. Kepulauan Yapen',
    'Kab. Lanny Jaya',
    'Kab. Mappi',
    'Kab. Memberamo Raya',
    'Kab. Membramo Tengah',
    'Kab. Merauke',
    'Kab. Mimika',
    'Kab. Nabire',
    'Kab. Nduga',
    'Kab. Paniai',
    'Kab. Pegunungan Bintang',
    'kab. Puncak',
    'Kab. Puncak Jaya',
    'Kab. Sarmi',
    'Kab. Supiori',
    'Kab. Tolikara',
    'Kab. Waropen',
    'Kab. Yahukimo',
    'Kab. Yalimo',
    'Kota Jayapura',
  ],
  PapuaBarat: [
    'Kab. Fak-Fak',
    'Kab. Kaimana',
    'Kab. Manokwari',
    'Kab. Manokwari Selatan',
    'Kab. Maybrat',
    'Kab. Pegunungan Arfak',
    'Kab. Raja Ampat',
    'Kab. Sorong',
    'Kab. Sorong Selatan',
    'Kab. Tambrauw',
    'Kab. Teluk Bintuni',
    'Kab. Teluk Wondama',
    'Kota Sorong',
  ],
  Riau: [
    'Kab. Bengkalis',
    'Kab. Indragiri Hilir',
    'Kab. Indragiri Hulu',
    'Kab. Kampar',
    'Kab. Kepulauan Meranti',
    'Kab. Kuantan Singingi',
    'Kab. Pelalawan',
    'Kab. Rokan Hilir',
    'Kab. Rokan Hulu',
    'Kab. Siak',
    'Kota Dumai',
    'Kota Pekanbaru',
  ],
  SulBar: [
    'Kab. Majene',
    'Kab. Mamasa',
    'Kab. Mamuju',
    'Kab. Mamuju Tengah',
    'Kab. Pasangkayu',
    'Kab. Polewali Mandar',
  ],
  SulSel: [
    'Kab. Bantaeng',
    'Kab. Barru',
    'Kab. Bone',
    'Kab. Bulukumba',
    'Kab. Enrekang',
    'Kab. Gowa',
    'Kab. Jeneponto',
    'Kab. Kepulauan Selayar',
    'Kab. Luwu',
    'Kab. Luwu Timur',
    'Kab. Luwu Utara',
    'Kab. Maros',
    'Kab. Pangkajene Kepulauan',
    'Kab. Pinrang',
    'Kab. Sidenreng Rappang',
    'Kab. Sinjai',
    'Kab. Soppeng',
    'Kab. Takalar',
    'Kab. Tana Toraja',
    'Kab. Toraja Utara',
    'Kab. Wajo',
    'Kota Makassar',
    'Kota Palopo',
    'Kota Parepare',
  ],
  SulTengah: [
    'Kab. Banggai',
    'Kab. Banggai Kepulauan',
    'Kab. Banggai Laut',
    'Kab. Buol',
    'Kab. Donggala',
    'Kab. Morowali',
    'Kab. Morowali Utara',
    'Kab. Parigi Moutong',
    'Kab. Poso',
    'Kab. Sigi',
    'Kab. Tojo Una-Una',
    'Kab. Tolitoli',
    'Kota Palu',
  ],
  SulTenggara: [
    'Kab. Bombana',
    'Kab. Buton',
    'Kab. Buton Selatan',
    'Kab. Buton Tengah',
    'Kab. Buton Utara',
    'Kab. Kolaka',
    'Kab. Kolaka Timur',
    'Kab. Kolaka Utara',
    'Kab. Konawe',
    'Kab. Konawe Kepulauan',
    'Kab. Konawe Selatan',
    'Kab. Konawe Utara',
    'Kab. Muna',
    'Kab. Muna Barat',
    'Kab. Wakatobi',
    'Kota Baubau',
    'Kota Kendari',
  ],
  SulUt: [
    'Kab. Bolaang Mongondow',
    'Kab. Bolaang Mongondow Selatan',
    'Kab. Bolaang Mongondow Timur',
    'Kab. Bolaang Mongondow Utara',
    'Kab. Kep. Sangihe',
    'Kab. Kepulauan Siau Tagulandang Biaro',
    'Kab. Kepulauan Talaud',
    'Kab. Minahasa',
    'Kab. Minahasa Selatan',
    'Kab. Minahasa Tenggara',
    'Kab. Minahasa Utara',
    'Kota Bitung',
    'Kota Kotamobagu',
    'Kota Manado',
    'Kota Tomohon',
  ],
  SumBar: [
    'Kab. Agam',
    'Kab. Dharmasraya',
    'Kab. Kepulauan Mentawai',
    'Kab. Lima Puluh Koto',
    'Kab. Padang Pariaman',
    'Kab. Pasaman',
    'Kab. Pasaman Barat',
    'Kab. Pesisir Selatan',
    'Kab. Sijunjung',
    'Kab. Solok',
    'Kab. Solok Selatan',
    'Kab. Tanah Datar',
    'Kota Bukittinggi',
    'Kota Padang',
    'Kota Padang Panjang',
    'Kota Pariaman',
    'Kota Payakumbuh',
    'Kota Sawah Lunto',
    'Kota Solok',
  ],
  SumSel: [
    'Kab. Banyuasin',
    'Kab. Empat Lawang',
    'Kab. Lahat',
    'Kab. Muara Enim',
    'Kab. Musi Banyuasin',
    'Kab. Musi Rawas',
    'Kab. Musi Rawas Utara',
    'Kab. Ogan Ilir',
    'Kab. Ogan Komering Ilir',
    'Kab. Ogan Komering Ulu',
    'Kab. Ogan Komering Ulu Selatan',
    'Kab. Ogan Komering Ulu Timur',
    'Kab. Penukal Abab Lematang Ilir',
    'Kota Lubuk Linggau',
    'Kota Pagar Alam',
    'Kota Palembang',
    'Kota Prabumulih',
  ],
  SumUt: [
    'Kab. Asahan',
    'Kab. Batubara',
    'Kab. Dairi',
    'Kab. Deli Serdang',
    'Kab. Humbang Hasudutan',
    'Kab. Karo',
    'Kab. Labuhan Batu',
    'Kab. Labuhan Batu Selatan',
    'Kab. Labuhan Batu Utara',
    'Kab. Langkat',
    'Kab. Mandailing Natal',
    'Kab. Nias',
    'Kab. Nias Barat',
    'Kab. Nias Selatan',
    'Kab. Nias Utara',
    'Kab. Padang Lawas',
    'Kab. Padang Lawas utara',
    'Kab. Pakpak Bharat',
    'Kab. Samosir',
    'Kab. Serdang Bedagai',
    'Kab. Simalungun',
    'Kab. Tapanuli Selatan',
    'Kab. Tapanuli Tengah',
    'Kab. Tapanuli Utara',
    'Kab. Toba',
    'Kota Binjai',
    'Kota Gunungsitoli',
    'Kota Medan',
    'Kota Padang Sidimpuan',
    'Kota Pematangsiantar',
    'Kota Sibolga',
    'Kota Tanjung Balai',
    'Kota Tebing Tinggi',
  ],
  default: ['Mohon pilih provinsi terlebih dahulu'],
};

export default CitiesList;
