const UniversityList = [
  { institusi: 'Universitas Gadjah Mada' },
  { institusi: 'Universitas Indonesia' },
  { institusi: 'Universitas Pendidikan Indonesia' },
  { institusi: 'Universitas Diponegoro' },
  { institusi: 'Universitas Brawijaya' },
  { institusi: 'Universitas Negeri Yogyakarta' },
  { institusi: 'Universitas Lampung' },
  { institusi: 'Universitas Airlangga' },
  { institusi: 'Institut Pertanian Bogor' },
  { institusi: 'Universitas Negeri Semarang' },
  { institusi: 'Universitas Muhammadiyah Surakarta' },
  { institusi: 'Institut Teknologi Bandung' },
  { institusi: 'Universitas Negeri Malang' },
  { institusi: 'Universitas Sumatera Utara' },
  { institusi: 'Universitas Muhammadiyah Yogyakarta' },
  { institusi: 'Universitas Bina Nusantara' },
  { institusi: 'Universitas Telkom' },
  { institusi: 'Institut Teknologi Sepuluh Nopember' },
  { institusi: 'Universitas Jember' },
  { institusi: 'Universitas Udayana' },
  { institusi: 'Universitas Islam Negeri Maulana Malik Ibrahim Malang' },
  { institusi: 'Universitas Andalas' },
  { institusi: 'Universitas Sebelas Maret' },
  { institusi: 'Universitas Hasanuddin' },
  { institusi: 'Universitas Islam Negeri Syarif Hidayatullah Jakarta' },
  { institusi: 'Universitas Muhammadiyah Malang' },
  { institusi: 'Universitas Islam Negeri Sunan Ampel Surabaya' },
  { institusi: 'Universitas Islam Indonesia' },
  { institusi: 'Universitas Islam Negeri Walisongo' },
  { institusi: 'Universitas Islam Negeri Sulthan Syarif Kasim Riau' },
  { institusi: 'Universitas Pasundan' },
  { institusi: 'Universitas Negeri Surabaya' },
  { institusi: 'Universitas Syiah Kuala' },
  { institusi: 'Universitas Mercu Buana' },
  { institusi: 'Universitas Gunadarma' },
  { institusi: 'Universitas Islam Negeri Sunan Kalijaga Yogyakarta' },
  { institusi: 'Universitas Jambi' },
  { institusi: 'Universitas Ahmad Dahlan' },
  { institusi: 'Universitas Dian Nuswantoro' },
  { institusi: 'Universitas Sriwijaya' },
  { institusi: 'Universitas Islam Negeri Alauddin Makassar' },
  { institusi: 'Universitas Sam Ratulangi' },
  { institusi: 'Universitas Negeri Padang' },
  { institusi: 'Universitas Sanata Dharma' },
  { institusi: 'Universitas Narotama' },
  { institusi: 'Universitas Komputer Indonesia' },
  { institusi: 'Universitas Mataram' },
  { institusi: 'Universitas Jenderal Soedirman' },
  { institusi: 'Universitas Muhammadiyah Purwokerto' },
  { institusi: 'Universitas Atma Jaya Yogyakarta' },
  { institusi: 'Universitas Padjadjaran' },
  { institusi: 'Universitas Bengkulu' },
  { institusi: 'Universitas Muhammadiyah Sumatera Utara' },
  { institusi: 'Universitas Islam Sultan Agung' },
  { institusi: 'Universitas Esa Unggul' },
  { institusi: 'Universitas Islam Negeri Sunan Gunung Djati' },
  { institusi: 'Universitas Kristen Petra' },
  { institusi: 'Universitas Muhammadiyah Ponorogo' },
  { institusi: 'Universitas Pendidikan Ganesha' },
  { institusi: 'Universitas Riau' },
  { institusi: 'Universitas Muhammadiyah Semarang' },
  { institusi: 'Universitas Islam Bandung' },
  { institusi: 'Universitas Sarjanawiyata Tamansiswa' },
  { institusi: 'Universitas Islam Negeri Sumatera Utara' },
  { institusi: 'Universitas Mulawarman' },
  { institusi: 'Universitas Widyatama' },
  { institusi: 'Universitas Tanjungpura' },
  { institusi: 'Universitas Tadulako' },
  { institusi: 'Universitas Negeri Medan' },
  { institusi: 'Universitas Islam Negeri Raden Intan Lampung Bandar' },
  { institusi: 'Universitas Lambung Mangkurat' },
  { institusi: 'Institut Seni Indonesia Surakarta' },
  { institusi: 'Universitas Negeri Makassar' },
  { institusi: 'Universitas Negeri Jakarta' },
  { institusi: 'Universitas Trunojoyo Madura' },
  { institusi: 'Universitas Pelita Harapan' },
  { institusi: 'Universitas Darma Persada' },
  { institusi: 'Universitas Medan Area' },
  { institusi: 'Universitas Kristen Maranatha' },
  { institusi: 'Universitas Pembangunan Nasional Veteran Jawa Timur' },
  { institusi: 'Universitas Surabaya' },
  { institusi: 'Universitas Mercu Buana Yogyakarta' },
  { institusi: 'Universitas Muhammadiyah Metro' },
  { institusi: 'Universitas Katolik Soegijapranata' },
  { institusi: 'Universitas Katolik Parahyangan' },
  { institusi: 'Universitas PGRI Madiun' },
  { institusi: 'Universitas Muhammadiyah Sidoarjo' },
  { institusi: 'Universitas Islam Negeri Raden Fatah' },
  { institusi: 'Universitas Swadaya Gunung Jati' },
  { institusi: 'Universitas Katolik Indonesia Atma Jaya' },
  { institusi: 'Universitas 17 Agustus 1945 Surabaya' },
  { institusi: 'Institut Teknologi Nasional' },
  { institusi: 'Universitas Islam Negeri Ar-Raniry' },
  { institusi: 'Institut Seni Indonesia Denpasar' },
  { institusi: 'Universitas Kristen Satya Wacana' },
  { institusi: 'Universitas Trisakti' },
  { institusi: 'Universitas Halu Oleo' },
  { institusi: 'Universitas Bina Darma' },
  { institusi: 'Universitas Muria Kudus' },
  { institusi: 'Universitas Wahid Hasyim' },
];

export default UniversityList;
