const WorkList = [
  { field: 'Accounting' },
  { field: 'Admin' },
  { field: 'Auditor' },
  { field: 'Brand Partnership' },
  { field: 'Business Intelligence' },
  { field: 'Business Analyst' },
  { field: 'Business Development' },
  { field: 'Consultant' },
  { field: 'Cashier' },
  { field: 'Chef' },
  { field: 'Content Creator' },
  { field: 'Copy Writer' },
  { field: 'Customer Service' },
  { field: 'Programmer' },
  { field: 'Data Analyst' },
  { field: 'Developer' },
  { field: 'Digital Marketing' },
  { field: 'Distributor' },
  { field: 'Engineer' },
  { field: 'Finance' },
  { field: 'Graphic Design' },
  { field: 'Human Resource' },
  { field: 'Information Technology Specialist' },
  { field: 'Legal' },
  { field: 'Management Trainee' },
  { field: 'Marketing' },
  { field: 'Merchandiser' },
  { field: 'Operator' },
  { field: 'Procurement' },
  { field: 'Production' },
  { field: 'Teacher' },
  { field: 'Project Management' },
  { field: 'Public Relation' },
  { field: 'Purchasing' },
  { field: 'Quality & Assurance' },
  { field: 'Research & Development' },
  { field: 'Sales' },
  { field: 'Secretary' },
  { field: 'Operational Staff/ Officer' },
  { field: 'Supervisor' },
  { field: 'Talent Acquisition' },
  { field: 'Technician' },
  { field: 'UI/ UX' },
  { field: 'Videographer' },
  { field: 'Forcasting, Planning, and Analysis' },
  { field: 'General Affair' },
  { field: 'Customer Relation Management' },
  { field: 'Social Media Executive' },
  { field: 'Risk Management' },
  { field: 'Media Executive' },
  { field: 'Brand Acquisition' },
  { field: 'Learning & Development' },
  { field: 'Social Media Admin' },
  { field: 'Supply Chain Management' },
  { field: 'Translator' },
  { field: 'Analyst' },
  { field: 'Assistant' },
  { field: 'Content Writer' },
];
export default WorkList;
